#!/bin/bash
# =============================================================================
# Liferay Monitor — Interactive Setup Script
# Run once before first start: bash scripts/setup.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

echo ""
echo "=============================================="
echo "  Liferay Monitor Stack — Setup"
echo "=============================================="
echo ""

# --- Detect existing Liferay Docker networks ---
echo "Detecting Docker networks..."
NETWORKS=$(docker network ls --format "{{.Name}}" 2>/dev/null | grep -v "bridge\|host\|none\|lf-monitor" || true)
echo ""
echo "Available Docker networks:"
echo "$NETWORKS"
echo ""

# --- Detect running containers ---
echo "Detecting running containers..."
CONTAINERS=$(docker ps --format "{{.Names}}" 2>/dev/null || true)
echo "Running containers:"
echo "$CONTAINERS"
echo ""

# --- Prompt for configuration ---
read -p "Liferay Docker network name [liferay-backend]: " LIFERAY_NETWORK
LIFERAY_NETWORK=${LIFERAY_NETWORK:-liferay-backend}

read -p "Liferay container name [liferay]: " LIFERAY_CONTAINER
LIFERAY_CONTAINER=${LIFERAY_CONTAINER:-liferay}

read -p "Nginx container name [web-server]: " NGINX_CONTAINER
NGINX_CONTAINER=${NGINX_CONTAINER:-web-server}

read -p "PostgreSQL container name [db]: " DB_CONTAINER
DB_CONTAINER=${DB_CONTAINER:-db}

read -p "PostgreSQL host (usually same as container name) [db]: " POSTGRES_HOST
POSTGRES_HOST=${POSTGRES_HOST:-db}

read -p "PostgreSQL port [5432]: " POSTGRES_PORT
POSTGRES_PORT=${POSTGRES_PORT:-5432}

read -p "PostgreSQL username [liferay]: " POSTGRES_USER
POSTGRES_USER=${POSTGRES_USER:-liferay}

read -s -p "PostgreSQL password: " POSTGRES_PASSWORD
echo ""

read -p "PostgreSQL database name [portal737]: " POSTGRES_DB
POSTGRES_DB=${POSTGRES_DB:-portal737}

read -p "Liferay JMX host [liferay]: " LIFERAY_JMX_HOST
LIFERAY_JMX_HOST=${LIFERAY_JMX_HOST:-liferay}

read -p "Liferay JMX port [9999]: " LIFERAY_JMX_PORT
LIFERAY_JMX_PORT=${LIFERAY_JMX_PORT:-9999}

read -p "Nginx stub_status URL [http://web-server/stub_status]: " NGINX_URL
NGINX_URL=${NGINX_URL:-http://web-server/stub_status}

read -p "Grafana root URL [http://localhost:3000]: " GRAFANA_ROOT_URL
GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3000}

read -s -p "Grafana admin password: " GRAFANA_PASSWORD
echo ""

# --- Verify network exists ---
echo ""
echo "Verifying Docker network '$LIFERAY_NETWORK' exists..."
if ! docker network ls --format "{{.Name}}" | grep -q "^${LIFERAY_NETWORK}$"; then
    echo "WARNING: Network '$LIFERAY_NETWORK' not found."
    echo "Make sure your Liferay stack is running before starting this monitor."
fi

# --- Write .env ---
cat > "$ENV_FILE" << EOF
# Generated by setup.sh on $(date)
# Re-run scripts/setup.sh to reconfigure

LIFERAY_NETWORK=${LIFERAY_NETWORK}
LIFERAY_CONTAINER=${LIFERAY_CONTAINER}
NGINX_CONTAINER=${NGINX_CONTAINER}
DB_CONTAINER=${DB_CONTAINER}

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

LIFERAY_JMX_HOST=${LIFERAY_JMX_HOST}
LIFERAY_JMX_PORT=${LIFERAY_JMX_PORT}

NGINX_STUB_STATUS_URL=${NGINX_URL}

GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}
GRAFANA_SERVE_FROM_SUBPATH=false
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

PROMETHEUS_RETENTION=30d
EOF

echo ""
echo "Configuration saved to .env"

# --- Create data directories ---
mkdir -p "$ROOT_DIR/monitoring/prometheus/data"
mkdir -p "$ROOT_DIR/monitoring/grafana/data"
echo "Data directories created."

# --- Fix permissions for Grafana ---
chown -R 472:472 "$ROOT_DIR/monitoring/grafana/data" 2>/dev/null || \
  chmod -R 777 "$ROOT_DIR/monitoring/grafana/data"
echo "Grafana data directory permissions set."

echo ""
echo "=============================================="
echo "  Setup complete! Next steps:"
echo "=============================================="
echo ""
echo "1. Add JMX to Liferay setenv.sh:"
echo "   See: docs/01-setenv-additions.sh"
echo ""
echo "2. Add stub_status to nginx config:"
echo "   See: docs/02-nginx-additions.conf"
echo ""
echo "3. Expose JMX port in your docker-compose.yml:"
echo "   See: docs/03-liferay-compose-additions.yml"
echo ""
echo "4. Restart Liferay to activate JMX:"
echo "   docker-compose restart liferay"
echo ""
echo "5. Start the monitor stack:"
echo "   docker-compose up -d"
echo ""
echo "6. Open Grafana at: ${GRAFANA_ROOT_URL}"
echo "   Login: admin / (your password)"
echo ""
